### PR TITLE
Allow user to specify their own BIP32 Root Key.

### PR DESCRIPTION
**Pull request by dooglus**
https://bitcointalk.org/index.php?topic=293472.msg12328192#msg12328192 asked how to generate a list of addresses and private keys given an xprv key rather than a 12 word seed.

I made these changes to make it possible.

### CODE REVIEW

**Comment by dangershony** [comment]
Hi,
Is this going to be merged anytime soon?
I would like to refer to here from coinvault.io FAQ for recovering keys
Anything I can help with?
Thanks

**Comment by iancoleman** [comment]
This will not be merged, but I am working on this feature today so should be available soon.

Reason for not merging (and the long delay in implementing it myself) is the implementation a bit more complex than the pull request code:

When changing derivation paths, it is unknown whether to derive from bip39 mnemonic or from bip32 root key, which may be different from each other. This pull request will result in only deriving from mnemonic, even if a custom root key is specified.

To reproduce this:

* generate random mnemonic
* change the root key to something else
* change the derivation path
* the addresses are generated using the mnemonic, not the new root key, which is unexpected behavior.

I'm currently working on this feature so hope to have it available within the next 24h.

Thanks for the reminder!

**Comment by iancoleman** [comment]
This has been implemented in https://github.com/dcpos/bip39/commit/efe41586705d3eba480da31bb1002c4e54e73ef0 `BIP32 Root Key can be specified by user`

This includes a refactor of the generation mechanism so it doesn't try to use the mnemonic if a custom root key has been specified.

Thanks for the reminder @dangershony and thanks for the motivation @dooglus

**Comment by dangershony** [comment]
Excellent jog thanks, 
I'll be submitting a pull request to add some more coins later.

**Pull request closed without merging**
